
name: MagicBell Swift Tests

on:
  pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.3", "5.4", "5.5"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2.1.0
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SPM Cache
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ matrix.swift }}
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build